name: runs actions

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout action
        uses: actions/checkout@v1
      - name: list file
        run: |
          pwd
          ls