name: runs actions

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:

      - name: checkout action
        uses: actions/checkout@v1
      - name: setup java jdk
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64
      - name: compile the code
        run: mvn clean test -Dsurefire.suiteXmlFiles=testng.xml